; Listing generated by Microsoft (R) Optimizing Compiler Version 18.00.21005.1 

	TITLE	C:\Users\ChangChang\Documents\Visual Studio 2013\Projects\1일차\1일차\1_템플릿개념.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	_main
PUBLIC	??$square@H@@YAHH@Z				; square<int>
PUBLIC	??$square@N@@YANN@Z				; square<double>
PUBLIC	??$square@F@@YAFF@Z				; square<short>
PUBLIC	__real@400a666666666666
EXTRN	__fltused:DWORD
;	COMDAT __real@400a666666666666
CONST	SEGMENT
__real@400a666666666666 DQ 0400a666666666666r	; 3.3
CONST	ENDS
; Function compile flags: /Odtp
; File c:\users\changchang\documents\visual studio 2013\projects\1일차\1일차\1_템플릿개념.cpp
;	COMDAT ??$square@F@@YAFF@Z
_TEXT	SEGMENT
_a$ = 8							; size = 2
??$square@F@@YAFF@Z PROC				; square<short>, COMDAT

; 32   : template <typename T>	T square ( T a ) { return a*a; }

	push	ebp
	mov	ebp, esp
	movsx	eax, WORD PTR _a$[ebp]
	movsx	ecx, WORD PTR _a$[ebp]
	imul	eax, ecx
	pop	ebp
	ret	0
??$square@F@@YAFF@Z ENDP				; square<short>
_TEXT	ENDS
; Function compile flags: /Odtp
; File c:\users\changchang\documents\visual studio 2013\projects\1일차\1일차\1_템플릿개념.cpp
;	COMDAT ??$square@N@@YANN@Z
_TEXT	SEGMENT
tv67 = -8						; size = 8
_a$ = 8							; size = 8
??$square@N@@YANN@Z PROC				; square<double>, COMDAT

; 32   : template <typename T>	T square ( T a ) { return a*a; }

	push	ebp
	mov	ebp, esp
	sub	esp, 8
	movsd	xmm0, QWORD PTR _a$[ebp]
	mulsd	xmm0, QWORD PTR _a$[ebp]
	movsd	QWORD PTR tv67[ebp], xmm0
	fld	QWORD PTR tv67[ebp]
	mov	esp, ebp
	pop	ebp
	ret	0
??$square@N@@YANN@Z ENDP				; square<double>
_TEXT	ENDS
; Function compile flags: /Odtp
; File c:\users\changchang\documents\visual studio 2013\projects\1일차\1일차\1_템플릿개념.cpp
;	COMDAT ??$square@H@@YAHH@Z
_TEXT	SEGMENT
_a$ = 8							; size = 4
??$square@H@@YAHH@Z PROC				; square<int>, COMDAT

; 32   : template <typename T>	T square ( T a ) { return a*a; }

	push	ebp
	mov	ebp, esp
	mov	eax, DWORD PTR _a$[ebp]
	imul	eax, DWORD PTR _a$[ebp]
	pop	ebp
	ret	0
??$square@H@@YAHH@Z ENDP				; square<int>
_TEXT	ENDS
; Function compile flags: /Odtp
; File c:\users\changchang\documents\visual studio 2013\projects\1일차\1일차\1_템플릿개념.cpp
_TEXT	SEGMENT
_s$ = -4						; size = 2
_main	PROC

; 35   : {

	push	ebp
	mov	ebp, esp
	push	ecx

; 36   : 	square(3);

	push	3
	call	??$square@H@@YAHH@Z			; square<int>

; 37   : 	square(3.3);

	add	esp, -4					; fffffffcH
	movsd	xmm0, QWORD PTR __real@400a666666666666
	movsd	QWORD PTR [esp], xmm0
	call	??$square@N@@YANN@Z			; square<double>
	fstp	ST(0)
	add	esp, 8

; 38   : 
; 39   : 	short s = 3;

	mov	eax, 3
	mov	WORD PTR _s$[ebp], ax

; 40   : 	square(s);	//1. sqaure(int) 버전을 사용하게 해줄 것이다.

	movzx	ecx, WORD PTR _s$[ebp]
	push	ecx
	call	??$square@F@@YAFF@Z			; square<short>
	add	esp, 4

; 41   : 				//2. square(short) 버전을 생성할것이다.
; 42   : 
; 43   : 	//cl.exe ( 컴파일러 )
; 44   : 	//C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\Tools\Shortcuts\VS2013용 개발자 명령 프롬프트
; 45   : 	//1) cl 1_템플릿개념 /FAs 
; 46   : 	//2) notepad 1_템플릿개념.asm
; 47   : 	
; 48   : 	
; 49   : 	
; 50   : 	
; 51   : 
; 52   : 	
; 53   : }

	xor	eax, eax
	mov	esp, ebp
	pop	ebp
	ret	0
_main	ENDP
_TEXT	ENDS
END
